# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 60dd7b5a557ea380ada28aadd07a269fa0c503f83efd15f3d3b0e1aaf6dc280de417017c41b90fa89ff2a1ce512929c21d04696ce4c54a130db67a3157307e05

test:
  secret_key_base: 22d254aa6474f1114103cc1c029901043d7bf30241b9ae20c6b7c5cb2f7a5c5c8ef7f0a2f573e8c2a25862f4a8c7a7b028bb64c43b51c46a9494cbe4444d9747

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
